### PR TITLE
abort on Invalid response (channel busy) or if unable to find best freq

### PR DESCRIPTION
**Pull request by scottleibrand**
This should allow us to use mmtune to (sometimes) detect if someone is already using the channel.  It will return true if everything is good, and it was able to find a freq that allowed it to talk on the pump.  If it detects the pump was talking to another rig, it will return false.

### CODE REVIEW

**Comment by scottleibrand** [comment]
I'm using it like this:
```
openaps alias add mmtune "! bash -c \"cd ~/src/minimed_rf/ && ruby -I lib bin/mmtune $ttyport $serial >/dev/null\""
openaps alias add preflight '! bash -c "rm -f monitor/clock.json && echo -n \"mmtune: \" && openaps mmtune && echo -n \"PREFLIGHT \" && openaps report invoke monitor/clock.json 2>/dev/null >/dev/null && grep -q T monitor/clock.json && echo OK || ( echo FAIL; openaps get-bg; sleep 120; exit 1 )"'
```

**Comment by jasoncalabrese** [comment]
Nice, I was hoping something like this would work.

While we're at it can we output as json?  Then we can include rssi and freq in the device status.

**Comment by ps2** [comment]
It looks like this sends out a lot of packets before backing off. Doing wakeup generates 100s of packets over several seconds. Those packets will certainly affect anything else trying to do comms at that point in time. Would it make more sense to just listen for a couple seconds to see if there are comms and then back off?

**Comment by scottleibrand** [comment]
That's the second thing it does.  The first thing it does is send a single model packet, and if it gets back an unexpected response, it never does the wakeup.  That said, I would love to have it also listen passively for a second or two to see if the pump is busy, I just didn't see an easy way to modify what was already there to accomplish that.

**Pull request closed without merging**
